#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
ONT cfDNA CpG 5mC Methylation QC

Description:
    Generates sample-level methylation QC metrics and visualizations for bedMethyl
    output from modkit. Calculates global and promoter-specific read depth and
    methylation profiles across TSS regions.

Dependencies:
    - Python >= 3.8
    - pandas, numpy, matplotlib, seaborn
    - bedtools (must be available in the system PATH)
"""

import argparse
import os
import subprocess
import tempfile
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.ticker import MaxNLocator
import matplotlib.ticker as ticker
import matplotlib.patheffects as path_effects

# ==========================================
# Global Visualization Configurations
# ==========================================
sns.set_theme(style="ticks", context="paper", font_scale=1.3)
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['pdf.fonttype'] = 42
plt.rcParams['axes.linewidth'] = 1.2

COLOR_COV = "#0072B2"
COLOR_METH = "#D55E00"
COLOR_BAR = "#7F8C8D"


def parse_args():
    parser = argparse.ArgumentParser(
        description="ONT cfDNA CpG 5mC Methylation QC Analysis and Visualization (Sample-Level)")
    parser.add_argument("-i", "--input", required=True,
                        help="Input bedMethyl.bgz file generated by modkit (bgzipped or uncompressed).")
    parser.add_argument("-b", "--bed", required=True,
                        help="BED file defining specific genomic regions (e.g., TSS/Promoters) for targeted spatial profiling.")
    parser.add_argument("-o", "--outdir", required=True,
                        help="Directory path for all output files (created automatically if it does not exist).")
    parser.add_argument("-p", "--prefix", default="sample_QC",
                        help="Prefix string for all generated output filenames (default: 'sample_QC').")
    parser.add_argument("--min-depth", type=int, default=0,
                        help="Minimum read depth threshold required to retain a CpG site for downstream analysis (default: 0).")
    parser.add_argument("--plots", type=str, default="all",
                        help="Comma-separated string of plot indices to generate (1-7), or 'all' for the complete suite (default: 'all').")
    parser.add_argument("--report-only", action="store_true",
                        help="Flag to bypass plot generation and exclusively output the JSON/CSV QC metrics reports.")
    parser.add_argument("--bin-size", type=int, default=50,
                        help="Bin resolution (in base pairs) for spatial distribution plotting relative to the TSS (default: 50).")
    return parser.parse_args()


def load_and_filter_global_data(input_file, min_depth):
    print(f"[1/5] Loading and filtering global methylation data (min_depth >= {min_depth})...")
    cols_to_use = [0, 1, 2, 3, 9, 10]
    col_names = ['chrom', 'start', 'end', 'mod_code', 'coverage', 'meth_level']

    comp = 'gzip' if input_file.endswith(('.bgz', '.gz')) else 'infer'
    df = pd.read_csv(input_file, sep='\t', header=None, usecols=cols_to_use,
                     names=col_names, comment='#', compression=comp)

    total_raw_cpgs = len(df[df['mod_code'] == 'm'])
    df_filtered = df[(df['mod_code'] == 'm') & (df['coverage'] >= min_depth)].copy()

    print(f"      -> Retained {len(df_filtered):,} / {total_raw_cpgs:,} 5mC CpGs.")
    return df_filtered, total_raw_cpgs


def intersect_with_promoter(df_global, bed_file):
    print("[2/5] Intersecting with promoter regions using bedtools...")
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_bed_path = os.path.join(temp_dir, "global_temp.bed")
        intersect_out_path = os.path.join(temp_dir, "intersected.bed")

        df_global[['chrom', 'start', 'end', 'coverage', 'meth_level']].to_csv(
            temp_bed_path, sep='\t', index=False, header=False
        )

        cmd = f"bedtools intersect -a {temp_bed_path} -b {bed_file} -wa -wb > {intersect_out_path}"
        subprocess.run(cmd, shell=True, check=True, executable='/bin/bash')

        intersect_cols = ['chrom', 'start', 'end', 'coverage', 'meth_level',
                          'p_chrom', 'p_start', 'p_end', 'p_name', 'p_strand']
        df_promoter = pd.read_csv(intersect_out_path, sep='\t', header=None, names=intersect_cols)

    print(f"      -> Found {len(df_promoter):,} CpGs falling into promoter regions.")
    return df_promoter


def calculate_distance_to_tss(df_promoter):
    print("[3/5] Calculating spatial distance to TSS...")
    df_promoter['TSS'] = df_promoter['p_start'] + 2000
    conditions = [df_promoter['p_strand'] == '+', df_promoter['p_strand'] == '-']
    choices = [df_promoter['start'] - df_promoter['TSS'], df_promoter['TSS'] - df_promoter['start']]
    df_promoter['distance_to_TSS'] = np.select(conditions, choices, default=np.nan)
    return df_promoter


def generate_qc_report(df_global, df_promoter, total_raw_cpgs, args):
    print("[4/5] Generating Markdown QC report...")

    g_total = int(len(df_global))
    g_mean_cov = float(df_global['coverage'].mean()) if g_total > 0 else 0
    g_med_cov = float(df_global['coverage'].median()) if g_total > 0 else 0
    g_max_cov = int(df_global['coverage'].max()) if g_total > 0 else 0
    g_99_cov = float(df_global['coverage'].quantile(0.99)) if g_total > 0 else 0
    g_mean_meth = float(df_global['meth_level'].mean()) if g_total > 0 else 0
    g_med_meth = float(df_global['meth_level'].median()) if g_total > 0 else 0

    p_total = int(len(df_promoter))
    p_mean_cov = float(df_promoter['coverage'].mean()) if p_total > 0 else 0
    p_med_cov = float(df_promoter['coverage'].median()) if p_total > 0 else 0
    p_max_cov = int(df_promoter['coverage'].max()) if p_total > 0 else 0
    p_99_cov = float(df_promoter['coverage'].quantile(0.99)) if p_total > 0 else 0
    p_mean_meth = float(df_promoter['meth_level'].mean()) if p_total > 0 else 0
    p_med_meth = float(df_promoter['meth_level'].median()) if p_total > 0 else 0

    report = {
        "Analysis_Parameters": {
            "Input_File": args.input,
            "TSS_BED": args.bed if hasattr(args, 'bed') and args.bed else "None",
            "Min_Depth": args.min_depth
        },
        "Global_Metrics": {
            "Total_Raw_5mC_CpGs": int(total_raw_cpgs),
            "Total_Analyzed_CpGs": g_total,
            "Mean_Coverage_Depth": g_mean_cov,
            "Median_Coverage_Depth": g_med_cov,
            "Max_Coverage_Depth": g_max_cov,
            "Coverage_99th_Percentile": g_99_cov,
            "Mean_Methylation_Level": g_mean_meth,
            "Median_Methylation_Level": g_med_meth
        },
        "Promoter_Metrics": {
            "Total_Analyzed_CpGs": p_total,
            "Mean_Coverage_Depth": p_mean_cov,
            "Median_Coverage_Depth": p_med_cov,
            "Max_Coverage_Depth": p_max_cov,
            "Coverage_99th_Percentile": p_99_cov,
            "Mean_Methylation_Level": p_mean_meth,
            "Median_Methylation_Level": p_med_meth
        }
    }

    md_file = os.path.join(args.outdir, f"{args.prefix}_QC_report.md")

    with open(md_file, 'w') as f:
        f.write(f"# Sample-Level Methylation QC Report ({args.prefix})\n\n")

        f.write("## Analysis Parameters\n")
        f.write(f"- Input File: `{os.path.basename(args.input)}`\n")
        if hasattr(args, 'bed') and args.bed:
            f.write(f"- TSS BED File: `{os.path.basename(args.bed)}`\n")
        f.write(f"- Min Depth Threshold: **{args.min_depth}x**\n\n")

        f.write("## Global Metrics\n")
        f.write(f"- Total Raw 5mC CpGs: **{int(total_raw_cpgs):,}**\n")
        f.write(f"- Total Analyzed CpGs (Passed Filter): **{g_total:,}**\n")
        f.write(f"- Mean Coverage Depth: {g_mean_cov:.2f}x\n")
        f.write(f"- Median Coverage Depth: {g_med_cov:.2f}x\n")
        f.write(f"- Max Coverage Depth: {g_max_cov}x\n")
        f.write(f"- Coverage 99th Percentile: {g_99_cov:.2f}x\n")

        # Format methylation levels to four decimal places for precision
        f.write(f"- Mean Methylation Level: {g_mean_meth:.4f}\n")
        f.write(f"- Median Methylation Level: {g_med_meth:.4f}\n\n")

        f.write("## Promoter Metrics\n")
        f.write(f"- Total Analyzed CpGs (Passed Filter): **{p_total:,}**\n")
        f.write(f"- Mean Coverage Depth: {p_mean_cov:.2f}x\n")
        f.write(f"- Median Coverage Depth: {p_med_cov:.2f}x\n")
        f.write(f"- Max Coverage Depth: {p_max_cov}x\n")
        f.write(f"- Coverage 99th Percentile: {p_99_cov:.2f}x\n")
        f.write(f"- Mean Methylation Level: {p_mean_meth:.4f}\n")
        f.write(f"- Median Methylation Level: {p_med_meth:.4f}\n")

    print(f"      -> Report saved to {md_file}")
    return report


def plot_figures(df_global, df_promoter, args):
    print("[5/5] Generating QC plots...")
    plot_list = [int(x) for x in args.plots.split(',')] if args.plots != 'all' else list(range(1, 8))
    pdf_path = os.path.join(args.outdir, f"{args.prefix}_All_QC_Plots.pdf")

    global_p99 = df_global['coverage'].quantile(0.99)
    promoter_p99 = df_promoter['coverage'].quantile(0.99) if len(df_promoter) > 0 else 100

    df_global_filtered = df_global[df_global['coverage'] <= global_p99]
    df_promoter_filtered = df_promoter[df_promoter['coverage'] <= promoter_p99] if len(df_promoter) > 0 else df_promoter

    edges = np.arange(-2000, 2000 + args.bin_size, args.bin_size)
    if any(p in plot_list for p in [5, 6, 7]):
        labels = edges[:-1] + (args.bin_size / 2)
        df_promoter['dist_bin'] = pd.cut(df_promoter['distance_to_TSS'], bins=edges, labels=labels)

        def q25(x): return x.quantile(0.25)

        def q75(x): return x.quantile(0.75)

        binned_stats = df_promoter.groupby('dist_bin', observed=False).agg(
            mean_depth=('coverage', 'mean'),
            depth_q25=('coverage', q25),
            depth_q75=('coverage', q75),
            mean_meth=('meth_level', 'mean'),
            meth_q25=('meth_level', q25),
            meth_q75=('meth_level', q75)
        ).reset_index()
        binned_stats['dist_bin'] = binned_stats['dist_bin'].astype(float)

    with PdfPages(pdf_path) as pdf:

        # ==========================================
        # [Figure 3]: Global CpG Methylation Distribution
        # ==========================================
        if 3 in plot_list:
            fig, ax = plt.subplots(figsize=(7, 5))
            sns.histplot(data=df_global, x='meth_level', bins=50, color=COLOR_METH, ax=ax, edgecolor='white',
                         linewidth=0.5)
            ax.set_title("Global: Methylation Distribution")
            ax.set_xlabel("Methylation Level (%)")
            ax.set_ylabel("CpG Count")
            ax.grid(axis='y', linestyle=':', alpha=0.6)
            sns.despine(ax=ax, trim=False)
            plt.tight_layout()
            plt.savefig(os.path.join(args.outdir, f"{args.prefix}_Fig03_Global_Methyl_Dist.png"), dpi=300)
            pdf.savefig(fig)
            plt.close()

        # ==========================================
        # [Figure 4]: Promoter CpG Methylation Distribution
        # ==========================================
        if 4 in plot_list:
            fig, ax = plt.subplots(figsize=(7, 5))
            sns.histplot(data=df_promoter, x='meth_level', bins=50, color=COLOR_METH, ax=ax, edgecolor='white',
                         linewidth=0.5)
            ax.set_title("Promoter: Methylation Distribution")
            ax.set_xlabel("Methylation Level (%)")
            ax.set_ylabel("CpG Count")
            ax.grid(axis='y', linestyle=':', alpha=0.6)
            sns.despine(ax=ax, trim=False)
            plt.tight_layout()
            plt.savefig(os.path.join(args.outdir, f"{args.prefix}_Fig04_Promoter_Methyl_Dist.png"), dpi=300)
            pdf.savefig(fig)
            plt.close()

        # ==========================================
        # [Figure 1]: Global Coverage Depth Histogram & CDF
        # ==========================================
        if 1 in plot_list:
            fig, ax1 = plt.subplots(figsize=(8, 5))

            max_x = int(global_p99)
            bins = np.arange(0, max_x + 2)

            ax1.hist(df_global_filtered['coverage'], bins=bins, color='tab:blue', alpha=0.6, edgecolor='white')
            ax1.set_xlabel("Read Depth")
            ax1.set_ylabel("CpG Count", color='tab:blue')
            ax1.tick_params(axis='y', labelcolor='tab:blue')

            ax2 = ax1.twinx()

            depth_counts = df_global['coverage'].value_counts().sort_index()
            x_vals = depth_counts.index.values
            cdf = depth_counts.cumsum().values / depth_counts.sum()

            if len(x_vals) > 0:
                if x_vals[0] > 0:
                    x_vals = np.insert(x_vals, 0, 0)
                    cdf = np.insert(cdf, 0, 0)
                elif x_vals[0] == 0:
                    x_vals = np.insert(x_vals, 0, -1)
                    cdf = np.insert(cdf, 0, 0)

            ax2.plot(x_vals, cdf, color='tab:orange', linewidth=2.5, label='Global CDF')

            target_ys = [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
            for ty in target_ys:
                idx = np.argmax(cdf >= ty)
                if idx == 0 or cdf[idx] < ty: continue

                x0, y0 = x_vals[idx - 1], cdf[idx - 1]
                x1, y1 = x_vals[idx], cdf[idx]
                exact_x = x0 + (ty - y0) * (x1 - x0) / (y1 - y0) if y1 != y0 else x1

                ax2.scatter(exact_x, ty, color='tab:orange', edgecolor='white', zorder=5, s=50)

                ax2.annotate(f"{exact_x:.1f}", (exact_x, ty),
                             textcoords="offset points", xytext=(12, 0),
                             ha='left', va='center', fontsize=10, color='tab:orange', fontweight='bold',
                             path_effects=[path_effects.withStroke(linewidth=1.5, foreground='white')])

            ax2.set_ylabel("Cumulative Fraction of CpGs", color='tab:orange')
            ax2.tick_params(axis='y', labelcolor='tab:orange')
            ax2.set_ylim(0, 1.05)

            ax1.set_xlim(left=0, right=max_x + 1)
            ax1.xaxis.set_major_locator(ticker.MaxNLocator(integer=True))
            ax1.set_title("Global: Read Depth Distribution & CDF")

            ax1.set_axisbelow(True)
            ax1.grid(axis='y', linestyle=':', color='gray', alpha=0.6)
            ax2.grid(False)

            plt.savefig(os.path.join(args.outdir, f"{args.prefix}_Fig01_Global_Depth_Dist.png"), dpi=300)
            pdf.savefig(fig)
            plt.close()

        # ==========================================
        # [Figure 2]: Promoter Coverage Depth Histogram & CDF
        # ==========================================
        if 2 in plot_list:
            fig, ax1 = plt.subplots(figsize=(8, 5))

            max_x = int(promoter_p99) if len(df_promoter) > 0 else 100
            bins = np.arange(0, max_x + 2)

            if len(df_promoter) > 0:
                ax1.hist(df_promoter_filtered['coverage'], bins=bins, color='tab:blue', alpha=0.6,
                         edgecolor='white')

            ax1.set_xlabel("Read Depth")
            ax1.set_ylabel("CpG Count", color='tab:blue')
            ax1.tick_params(axis='y', labelcolor='tab:blue')

            ax2 = ax1.twinx()

            if len(df_promoter) > 0:
                depth_counts = df_promoter['coverage'].value_counts().sort_index()
                x_vals = depth_counts.index.values
                cdf = depth_counts.cumsum().values / depth_counts.sum()

                if len(x_vals) > 0:
                    if x_vals[0] > 0:
                        x_vals = np.insert(x_vals, 0, 0)
                        cdf = np.insert(cdf, 0, 0)
                    elif x_vals[0] == 0:
                        x_vals = np.insert(x_vals, 0, -1)
                        cdf = np.insert(cdf, 0, 0)

                ax2.plot(x_vals, cdf, color='tab:orange', linewidth=2.5, label='Promoter CDF')

                target_ys = [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
                for ty in target_ys:
                    idx = np.argmax(cdf >= ty)
                    if idx == 0 or cdf[idx] < ty: continue

                    x0, y0 = x_vals[idx - 1], cdf[idx - 1]
                    x1, y1 = x_vals[idx], cdf[idx]
                    exact_x = x0 + (ty - y0) * (x1 - x0) / (y1 - y0) if y1 != y0 else x1

                    ax2.scatter(exact_x, ty, color='tab:orange', edgecolor='white', zorder=5, s=50)

                    ax2.annotate(f"{exact_x:.1f}", (exact_x, ty),
                                 textcoords="offset points", xytext=(12, 0),
                                 ha='left', va='center', fontsize=10, color='tab:orange', fontweight='bold',
                                 path_effects=[path_effects.withStroke(linewidth=1.5, foreground='white')])

            ax2.set_ylabel("Cumulative Fraction of CpGs", color='tab:orange')
            ax2.tick_params(axis='y', labelcolor='tab:orange')
            ax2.set_ylim(0, 1.05)

            ax1.set_xlim(left=0, right=max_x + 1)
            ax1.xaxis.set_major_locator(ticker.MaxNLocator(integer=True))
            ax1.set_title("Promoter: Read Depth Distribution & CDF")

            ax1.set_axisbelow(True)
            ax1.grid(axis='y', linestyle=':', color='gray', alpha=0.6)
            ax2.grid(False)

            plt.savefig(os.path.join(args.outdir, f"{args.prefix}_Fig02_Promoter_Depth_Dist.png"), dpi=300)
            pdf.savefig(fig)
            plt.close()

        # ==========================================
        # [Figure 5]: CpG Count Spatial Distribution vs Distance to TSS
        # ==========================================
        if 5 in plot_list:
            fig, ax = plt.subplots(figsize=(10, 5))
            ax.hist(df_promoter['distance_to_TSS'], bins=edges,
                    color=COLOR_BAR, alpha=0.8, edgecolor='white', linewidth=0.5)

            ax.set_title("CpG Distribution across TSS")
            ax.set_xlabel("Distance to TSS (bp)")
            ax.set_ylabel("CpG Count")
            ax.set_xlim(-2000, 2000)
            ax.grid(axis='y', linestyle=':', alpha=0.6)
            sns.despine(ax=ax, trim=False)
            plt.tight_layout()
            plt.savefig(os.path.join(args.outdir, f"{args.prefix}_Fig05_TSS_CpG_Dist.png"), dpi=300)
            pdf.savefig(fig)
            plt.close()

        # ==========================================
        # [Figure 6]: Spatial Mean Read Depth Profile with Interquartile Range (IQR)
        # ==========================================
        if 6 in plot_list:
            fig, ax = plt.subplots(figsize=(10, 5))
            ax.plot(binned_stats['dist_bin'].values, binned_stats['mean_depth'].values, color=COLOR_COV, linewidth=2.5,
                    label='Mean')
            ax.fill_between(binned_stats['dist_bin'], binned_stats['depth_q25'], binned_stats['depth_q75'],
                            color=COLOR_COV, alpha=0.2, label='IQR')
            ax.set_title("Read Depth Profile across TSS")
            ax.set_xlabel("Distance to TSS (bp)")
            ax.set_ylabel("Read Depth")
            ax.set_xlim(-2000, 2000)
            ax.legend(frameon=False, loc='upper right')
            ax.grid(axis='y', linestyle=':', alpha=0.6)
            sns.despine(ax=ax, trim=False)
            plt.tight_layout()
            plt.savefig(os.path.join(args.outdir, f"{args.prefix}_Fig06_TSS_Read_Depth_Profile.png"), dpi=300)
            pdf.savefig(fig)
            plt.close()

        # ==========================================
        # [Figure 7]: Spatial Mean Methylation Profile with Interquartile Range (IQR)
        # ==========================================
        if 7 in plot_list:
            fig, ax = plt.subplots(figsize=(10, 5))
            ax.plot(binned_stats['dist_bin'].to_numpy(), binned_stats['mean_meth'].to_numpy(), color=COLOR_METH,
                    linewidth=2.5, label='Mean')
            ax.fill_between(binned_stats['dist_bin'], binned_stats['meth_q25'], binned_stats['meth_q75'],
                            color=COLOR_METH, alpha=0.2, label='IQR')
            ax.set_title("Methylation Profile across TSS")
            ax.set_xlabel("Distance to TSS (bp)")
            ax.set_ylabel("Methylation Level (%)")
            ax.set_xlim(-2000, 2000)
            ax.set_ylim(-5, 105)
            ax.legend(frameon=False, loc='upper right')
            ax.grid(axis='y', linestyle=':', alpha=0.6)
            sns.despine(ax=ax, trim=False)
            plt.tight_layout()
            plt.savefig(os.path.join(args.outdir, f"{args.prefix}_Fig07_TSS_Methyl_Profile.png"), dpi=300)
            pdf.savefig(fig)
            plt.close()

    print(f"      -> All requested plots saved in PDF and as individual PNGs in '{args.outdir}'")


def main():
    args = parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    df_global, total_raw = load_and_filter_global_data(args.input, args.min_depth)
    df_promoter = intersect_with_promoter(df_global, args.bed)
    df_promoter = calculate_distance_to_tss(df_promoter)

    generate_qc_report(df_global, df_promoter, total_raw, args)

    if not args.report_only:
        plot_figures(df_global, df_promoter, args)

    print("[Done] QC Analysis successfully completed!")


if __name__ == "__main__":
    main()